module.exports = () => ( {
	plugins: [
		require('postcss-import'),
		require('postcss-url'),
		require('postcss-for'),
		require('postcss-each'),
		require('postcss-mixins'),
		require('postcss-custom-selectors'),
		require('postcss-selector-replace')({
			before: [ '[prefix]' ],
			after: [ 'sixa' ],
		}),
		require('postcss-nested-ancestors'),
		require('postcss-nested'),
		require('postcss-color-mod-function'),
		require('postcss-variables-prefixer')({
			prefix: 'sixa-',
			ignore: [ /range/ ],
		}),
		require('postcss-extend'),
		require('postcss-if-media'),
		require('postcss-important-startstop'),
		require('postcss-custom-media'),
		require('postcss-quantity-queries'),
		require('postcss-calc'),
		require('postcss-size'),
		require('postcss-flexbox'),
		require('postcss-position'),
		require('postcss-hidden'),
		require('postcss-short-border-radius'),
		require('postcss-transform-shortcut'),
		require('postcss-combine-media-query'),
		require('postcss-combine-duplicated-selectors'),
		require('postcss-discard-empty'),
		require('postcss-normalize'),
		require('postcss-input-range'),
		require('postcss-fontpath')({
			formats: [
				{ type: 'woff2', ext: 'woff2' },
				{ type: 'woff', ext: 'woff' },
				{ type: 'truetype', ext: 'ttf' },
			],
		}),
		require('autoprefixer')({ grid: true }),
	],
} );
